# Generated by Django 4.1 on 2022-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0002_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sVolume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
