# Generated by Django 4.1 on 2022-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0003_data_svolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_code', models.CharField(max_length=20)),
                ('month_name', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('month_lastrevenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('month_lastyear', models.DecimalField(decimal_places=2, max_digits=20)),
                ('month_lastmol', models.DecimalField(decimal_places=2, max_digits=20)),
                ('month_samemol', models.DecimalField(decimal_places=2, max_digits=20)),
                ('month_grand', models.DecimalField(decimal_places=2, max_digits=20)),
                ('month_lastgrand', models.DecimalField(decimal_places=2, max_digits=20)),
                ('month_forwardmol', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
