# Generated by Django 4.1 on 2022-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0004_monthlyrevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='year',
            field=models.CharField(max_length=6),
        ),
    ]
