# Generated by Django 4.1 on 2022-11-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0006_rename_month_monthlyrevenue_mmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrevenue',
            name='month_revenue',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
