# Generated by Django 4.1 on 2022-11-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0007_monthlyrevenue_month_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='sVolume',
            new_name='sChange',
        ),
        migrations.AddField(
            model_name='data',
            name='sDir',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sLastBestAskPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sLastBestAskVolume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sLastBestBidPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sLastBestBidVolume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sPE',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sTradeValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sTradeVolume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sTransaction',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
