# Generated by Django 4.1 on 2022-12-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0008_rename_svolume_data_schange_data_sdir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField()),
                ('tcode', models.CharField(max_length=20)),
                ('ma5', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ma10', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ma20', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
